apiVersion: apps/v1
kind: Deployment
metadata:
  name: getmyuri-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: getmyuri
  template:
    metadata:
      labels:
        app: getmyuri
    spec:
      containers:
        - name: getmyuri
          # The image tag will be substituted with the Jenkins build number
          image: yourdockerhubuser/getmyuri-backend:BUILD_NUMBER
          ports:
            - containerPort: 9090
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: getmyuri-secrets
                  key: MONGODB_URI
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: getmyuri-secrets
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: getmyuri-secrets
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: getmyuri-secrets
                  key: REDIS_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: getmyuri-secrets
                  key: PG_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: getmyuri-secrets
                  key: PG_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: getmyuri-secrets
                  key: PG_PASS
